Grupo1.AgendaDeTurnos/Controllers/CentrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Grupo1.AgendaDeTurnos.Database;
using Grupo1.AgendaDeTurnos.Models;
using Microsoft.AspNetCore.Authorization;

namespace Grupo1.AgendaDeTurnos.Controllers
{
    public class CentrosController : Controller
    {
        private readonly AgendaDeTurnosDbContext _context;

        public CentrosController(AgendaDeTurnosDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var agendaDeTurnosDbContext = _context.Centros.Include(c => c.Direccion);
            return View(await agendaDeTurnosDbContext.ToListAsync());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var centro = await _context.Centros
                .Include(c => c.Direccion)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (centro == null)
            {
                return NotFound();
            }

            return View(centro);
        }

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre")] Centro centro, string calle, int altura, string localidad, string provincia )
        {
            Direccion direccion = new Direccion()
            {
                Calle = calle,
                Altura = altura,
                Localidad = localidad,
                Provincia = provincia
            };
            centro.Direccion = direccion;
            if (ModelState.IsValid)
            {
                _context.Add(centro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           return View(centro);
        }
        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var centro = await _context.Centros
                .Include(c =>c.Direccion)
                .FirstOrDefaultAsync(c =>c.Id == id);
            if (centro == null)
            {
                return NotFound();
            }
            ViewBag.calle = centro.Direccion.Calle;
            ViewBag.altura = centro.Direccion.Altura;
            ViewBag.localidad = centro.Direccion.Localidad;
            ViewBag.provincia = centro.Direccion.Provincia;
            return View(centro);
        }

        [HttpPost]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nombre, Id")] Centro centro, string calle, string localidad, int altura, string provincia)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Direccion direccion = new Direccion()
                    {
                        Calle = calle,
                        Altura = altura,
                        Localidad = localidad,
                        Provincia = provincia
                    };
                    centro.Direccion = direccion;
                    _context.Update(centro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CentroExists(centro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(centro);
        }

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var centro = await _context.Centros
                .Include(c => c.Direccion)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (centro == null)
            {
                return NotFound();
            }

            return View(centro);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var centro = await _context.Centros.FindAsync(id);
            _context.Centros.Remove(centro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CentroExists(int id)
        {
            return _context.Centros.Any(e => e.Id == id);
        }
    }
}

Grupo1.AgendaDeTurnos/Controllers/TurnosController.cs
using Grupo1.AgendaDeTurnos.Database;
using Grupo1.AgendaDeTurnos.EnumList;
using Grupo1.AgendaDeTurnos.Extensions;
using Grupo1.AgendaDeTurnos.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Grupo1.AgendaDeTurnos.Controllers
{
    public class TurnosController : Controller
    {
        private int RANGO_TOLERANCIA_TURNO_MINUTOS = 15;
        private readonly AgendaDeTurnosDbContext _context;

        public TurnosController(AgendaDeTurnosDbContext context)
        {
            _context = context;
        }

        /* --------------------- MIS TURNOS (PACIENTE) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.CLIENTE))]
        public async Task<IActionResult> MisTurnos()
        {
            int pacienteId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            Paciente paciente = await _context.Pacientes
                .Include(t => t.Turnos)
                .ThenInclude(t => t.Centro)
                .Include(t => t.Turnos)
                .ThenInclude(t => t.Profesional)

                .FirstOrDefaultAsync(p => p.Id == pacienteId);

            return View(paciente.Turnos);
        }
        /* --------------------- NUEVO TURNO (PACIENTE) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.CLIENTE))]
        public IActionResult NuevoTurno()
        {
            ViewData["IdCentro"] = new SelectList(_context.Centros, "Id", "Nombre");
            ViewData["IdPrestacion"] = new SelectList(_context.Prestaciones, "Id", "Nombre");

            return View();
        }

        /* --------------------- NUEVO TURNO (PACIENTE)--------------------- */

        [HttpPost]
        [Authorize(Roles = nameof(RolesEnum.CLIENTE))]
        public IActionResult NuevoTurno(Turno turno, int IdPrestacion, int hora)
        {
            ViewData["IdCentro"] = new SelectList(_context.Centros, "Id", "Nombre");
            ViewData["IdPrestacion"] = new SelectList(_context.Prestaciones, "Id", "Nombre");

            int idCentro = turno.IdCentro;

            int pacienteId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            DateTime fechaYHoraDesde = turno.Fecha.AddHours(hora);

            if (DateTime.Now > fechaYHoraDesde)
            {
                ViewBag.ERROR = "El turno debe ser en el futuro ";
                return View();
            }

            List<Profesional> profesionales = _context.Profesionales
                                .Include(x => x.Turnos)
                                .Include(x => x.Prestacion)
                                .Where(prof =>
                                        prof.IdCentro == idCentro &&
                                        prof.IdPrestacion == IdPrestacion &&
                                        prof.Disponibilidades.Any(disponibilidad =>
                                            disponibilidad.Dia == turno.Fecha.DayOfWeek.ObtenerDiaPorDayOfWeek()
                                            &&
                                            disponibilidad.HoraDesde <= hora
                                            &&
                                            disponibilidad.HoraHasta >= (hora + prof.Prestacion.DuracionHoras)))
                                .ToList();



            foreach (Profesional profesional in profesionales)
            {
                if (!profesional.Turnos.Any(t =>
                        t.Fecha.Day == turno.Fecha.Day
                        &&
                         // fin de turno solicitado <= comienzo turno actual
                         //(hora.Hour + profesional.Prestacion.DuracionHoras) >= t.Fecha.Hour
                         hora > t.Fecha.Hour - profesional.Prestacion.DuracionHoras
                        &&
                        // fin de turno actual <= comienzo turno solicitado
                        (hora < (t.Fecha.Hour + profesional.Prestacion.DuracionHoras))))
                {
                    turno.IdCentro = idCentro;
                    turno.Profesional = profesional;
                    turno.Fecha = turno.Fecha.AddHours(hora);
                    turno.IdPaciente = pacienteId;
                    turno.Estado = EstadoTurnoEnum.PENDIENTE;


                    if (profesional.Turnos == null)
                    {
                        profesional.Turnos = new List<Turno>();

                    }
                    profesional.Turnos.Add(turno);
                    _context.Profesionales.Update(profesional);
                    _context.SaveChanges();

                    ViewBag.MENSAJE = "Su turno se reservo correctamente";
                    ViewBag.PROFESIONAL = "Se atendera con el profesional " + profesional.NombreYApellido;
                    ViewBag.DIA = turno.Fecha.FechaToString();
                    ViewBag.HORA = turno.Fecha.Hour + "hs";

                    return View();
                }
            }

            ViewBag.ERROR = "No hay profesionales disponibles en ese horario";
            return View();
        }

        /* --------------------- AGENDA DIARIA (PROFESIONAL) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.PROFESIONAL))]
        public async Task<IActionResult> AgendaDiaria()
        {
            DateTime fechaDeHoy = DateTime.Now;

            int profesionalId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            Profesional profesional = await _context.Profesionales
                .Include(p => p.Centro)
                .Include(p => p.Prestacion)
                .Include(p => p.Turnos)
                    .ThenInclude(t => t.Paciente)
                .Where(p => p.Id == profesionalId).SingleOrDefaultAsync();

            var listTurnosHoy = new List<Turno>();

            foreach (Turno t in profesional.Turnos)
            {
                DateTime rangoDesde = fechaDeHoy.AddMinutes(RANGO_TOLERANCIA_TURNO_MINUTOS * -1); //--> para pasar a menos 15
                DateTime rangoHasta = fechaDeHoy.AddMinutes(RANGO_TOLERANCIA_TURNO_MINUTOS);

                if (t.Fecha.Day == fechaDeHoy.Day)
                {
                    if (t.Fecha >= rangoDesde && t.Fecha <= rangoHasta && t.Estado != EstadoTurnoEnum.FINALIZADO)
                    {
                        //CAMBIO EL ESTADO PARA QUE DESDE EL FRONT SE PUEDA REALIZAR LA CONSULTA
                        t.Estado = EstadoTurnoEnum.ACTUAL;
                    }
                    listTurnosHoy.Add(t);
                }
            }
            if (listTurnosHoy.Count == 0)
            {
                ViewBag.MENSAJE = "No posee turnos reservados para el dia de hoy";
            }
            return View(listTurnosHoy);
        }

        /* --------------------- MI AGENDA (PROFESIONAL) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.PROFESIONAL))]
        public async Task<IActionResult> MiAgenda()
        {
            int profesionalId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            int mesActual = DateTime.Now.Month;
            int montoTotal = 0;
            Profesional profesional = await _context.Profesionales
                 .Include(p => p.Turnos)
                    .ThenInclude(t => t.Paciente)
                 .Include(p => p.Prestacion)
                 .Include(p => p.Centro)
                .SingleOrDefaultAsync(p => p.Id == profesionalId);

            List<Turno> turnosDelMesActual = new List<Turno>();

            foreach (Turno t in profesional.Turnos)
            {
                if (t.Fecha.Month == mesActual)
                {
                    turnosDelMesActual.Add(t);
                }
            }
            if (turnosDelMesActual.Count > 0)
            {
                foreach (Turno t in turnosDelMesActual)
                {
                    if (t.Estado == EstadoTurnoEnum.FINALIZADO)
                    {
                        montoTotal += profesional.Prestacion.Monto;
                    }
                }
            }
            ViewBag.Bienvenida = "Turnos para el mes de " + mesActual.getMesPorNumero();
            ViewBag.Monto = montoTotal;
            return View(turnosDelMesActual);
        }

        /* --------------------- COMENZAR CONSULTA (PROFESIONAL) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.PROFESIONAL))]
        public IActionResult ComenzarConsulta(int Id)
        {
            Turno turno = _context.Turnos
                 .Include(t => t.Paciente)
                 .Where(t => t.Id == Id)
                 .SingleOrDefault();

            return View(turno);
        }


        /* --------------------- FINALIZAR CONSULTA (PROFESIONAL) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.PROFESIONAL))]
        public IActionResult FinalizarConsulta(int Id)
        {
            Turno turno = _context.Turnos
                .Where(t => t.Id == Id)
                .SingleOrDefault();
            turno.Estado = EstadoTurnoEnum.FINALIZADO;
            _context.Turnos.Update(turno);
            _context.SaveChanges();
            return RedirectToAction("AgendaDiaria");

        }

        /* --------------------- INDEX (ADMIN) --------------------- */

        [HttpGet]
        [Authorize(Roles = nameof(RolesEnum.ADMINISTRADOR))]
        public async Task<IActionResult> Index()
        {
            var agendaDeTurnosDbContext = _context.Turnos.Include(t => t.Centro).Include(t => t.Paciente).Include(t => t.Profesional);
            return View(await agendaDeTurnosDbContext.ToListAsync());
        }

Grupo1.AgendaDeTurnos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@using System.Security.Claims;
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>


    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #303030!important;color:whitesmoke!important;">

    <nav id="menuT" class="navbar navbar-expand navbar-dark bg-primary">
        <a href="#menu-toggle" id="menu-toggle" class="navbar-brand">
            <span class="navbar-toggler-icon"></span>
        </a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarsTap" aria-controls="navbarsTap" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample02">
            <ul class="navbar-nav mr-auto">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav pull-xs-right">

                        <li class="nav-item">
                            <a class="btn btn-danger btn3d" asp-area="" asp-controller="Cuentas" asp-action="Salir">
                                    Salir
                            </a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav pull-xs-right">

                        <li class="nav-item">
                            <a type="button" class="btn btn-success btn3d" asp-area="" asp-controller="Cuentas" asp-action="Ingresar">
                                Iniciar Sesión
                            </a>
                        </li>

                        <li class="nav-item">
                            <a type="button" class="btn btn-info btn3d" asp-area="" asp-controller="Pacientes" asp-action="Create">
                                Registrarse
                            </a>
                        </li>
                    </ul>
                }
            </ul>
            <form class="form-inline my-2 my-md-0"> </form>
        </div>
    </nav>


    <div id="wrapper" class="toggled">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"> <a asp-controller="Home" asp-action="Index"> Turnos IRT </a> </li>


                @if (User.IsInRole(nameof(RolesEnum.CLIENTE)))
                {
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Turnos" asp-action="MisTurnos">Mis turnos</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Turnos" asp-action="NuevoTurno">Solicitar turno</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Pacientes" asp-action="EditMe">Editar mis datos</a>
                    </li>
                }
                @if (User.IsInRole(nameof(RolesEnum.PROFESIONAL)))
                {
                    <li class="">
                        <a class="nav-link text-dark" asp-controller="Turnos" asp-action="MiAgenda">Mi agenda</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-dark" asp-controller="Turnos" asp-action="AgendaDiaria">Turnos de hoy</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Profesionales" asp-action="EditMe">Editar mis datos</a>
                    </li>
                }
                
                @if (User.IsInRole(nameof(RolesEnum.ADMINISTRADOR)))
                {

                    <li onclick="tap()">
                        <a class="nav-link text-light" asp-controller="Profesionales" asp-action="Index">Profesionales</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Pacientes" asp-action="Index">Pacientes</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Administradores" asp-action="Index">Administradores</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Centros" asp-action="Index">Centros</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Prestaciones" asp-action="Index">Prestaciones</a>
                    </li>
                    <li class="">
                        <a class="nav-link text-light" asp-controller="Turnos" asp-action="Index">Turnos</a>
                    </li>

                }

            </ul>
        </div> 
        
        <div id="page-content-wrapper" >
            <div class="container-fluid"
                <partial name="_CookieConsentPartial" />
                <main role="main">
                    @RenderBody()
                </main>
            </div>

        </div> 
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script> <!-- Menu Toggle Script -->
    <script>


        $(function () {
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });

            $(window).resize(function (e) {
                if ($(window).width() <= 768) {
                    $("#wrapper").removeClass("toggled");
                } else {
                    $("#wrapper").addClass("toggled");
                }
            });
        });

    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>