Grupo1.AgendaDeTurnos/Controllers/CuentasController.cs
using Grupo1.AgendaDeTurnos.Database;
using Grupo1.AgendaDeTurnos.Extensions;
using Grupo1.AgendaDeTurnos.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Grupo1.AgendaDeTurnos.Controllers
{
    public class CuentasController : Controller
    {
        private readonly AgendaDeTurnosDbContext _context;

        public CuentasController(AgendaDeTurnosDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult Ingresar(string returnUrl)
        {
            //Se guardar URL
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }


        public IActionResult NoAutorizado()
        {
            return View();
        }

        private bool validarUsuarioExiste(string username)
        {
            if (_context.Profesionales.Any(p => p.Username.Equals(username))
                || _context.Pacientes.Any(p => p.Username.Equals(username))
                || _context.Administradores.Any(a => a.Username.Equals(username)))
            {
                return true;
            }
            else
            {
                return false;   
            }
        }
        private Usuario getUsuarioLogueado(Usuario admin, Usuario prof, Usuario paciente)
        {
            Usuario user = null;
            if(admin != null)
            {
                user = admin;
                return user;
            }else if(prof != null)
            {
                user = prof;
                return user;
            }else if(paciente != null)
            {
                user = paciente;
                return user;
            }
            return user;
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Ingresar(string username, string password, string returnUrl)
        {
            if (!string.IsNullOrWhiteSpace(username) && !string.IsNullOrWhiteSpace(password))
            {
                username = username.ToUpper();
                Usuario paciente = _context.Pacientes.FirstOrDefault(usr => usr.Username.ToUpper() == username);
                Usuario admin = _context.Administradores.FirstOrDefault(usr => usr.Username.ToUpper() == username);
                Usuario prof = _context.Profesionales.FirstOrDefault(usr => usr.Username.ToUpper() == username);

                Usuario usuario = getUsuarioLogueado(admin, prof, paciente);

                var passwordEncriptada = password.Encriptar();
                if (usuario!=null && usuario.Password.SequenceEqual(passwordEncriptada))
                {

                    ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                    identity.AddClaim(new Claim(ClaimTypes.Name, username));
                    identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()));
                    identity.AddClaim(new Claim(ClaimTypes.Role, usuario.Rol.ToString()));
                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);


                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    if (!string.IsNullOrWhiteSpace(returnUrl))
                        return Redirect(returnUrl);

                    TempData["primerLogin"] = true;

                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }
            }

            //En caso de datos incorrectos
            ViewBag.Error = "Usuario o contraseña incorrectos";
            ViewBag.UserName = username;
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }
        public async Task<IActionResult> Salir()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Grupo1.AgendaDeTurnos/Views/Cuentas/Ingresar.cshtml
@{
    ViewData["Title"] = "Ingresar";
}

<div class="text-center">
    <h1>@($"{ this.ViewData["Title"] }") </h1>
</div>




<div class="row bounceIn bounceInLeft">
    <div class="col-lg-offset-4 col-md-4">
        <form method="post" asp-controller="Cuentas" asp-action="Ingresar">

            <input type="hidden" value="@ViewBag.ReturnUrl" name="returnUrl" />
            <div class="text-danger">
                @ViewBag.Error
            </div>
            <div class="form-group">
                <label laber-for="username" class="control-label">Nombre de usuario:</label>
                <input name="username" class="form-control" type="text" value="@ViewBag.Username" />
            </div>

            <div class="form-group">
                <label label-for="Password" class="control-label">Contraseña:</label>
                <input name="password" class="form-control" type="password" />
            </div>

            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-success btn3d" />
            </div>
        </form>
    </div>

    <div>
        <p>Para ingresar como <strong>Paciente</strong>      ==> user: <strong>paciente</strong> pass: <strong>Paciente123</strong></p>
        <p>Para ingresar como <strong>Profesional</strong>   ==> user: <strong>prof</strong> pass: <strong>Profesional123</strong></p>
        <p>Para ingresar como <strong>Administrador</strong> ==> user: <strong>admin</strong> pass: <strong>admin</strong></p>
        <br />
        <p>Para ingresar como <strong>Profesional (Marchese)</strong> ==> user: <strong>fmarchese</strong> pass: <strong>Marchese123</strong></p>
        <p>Para ingresar como <strong>Paciente (Capelli)</strong> ==> user: <strong>rcapelli</strong> pass: <strong>Capelli123</strong></p>

    </div>
</div>

Grupo1.AgendaDeTurnos/Views/Cuentas/NoAutorizado.cshtml
@{
    ViewData["Title"] = "No Autorizado";
}

<h1>No Autorizado</h1>
<p>
    El usuario no se encuentra autorizado para acceder al recurso solicitado.
</p>

Grupo1.AgendaDeTurnos/Views/Cuentas/Registrar.cshtml
@model Grupo1.AgendaDeTurnos.Models.Paciente

@{
    ViewData["Title"] = "Registrar";
}


<h1>@($"{ this.ViewData["Title"] }") </h1>

<div class="bounceIn bounceInRight">
    <div class="text-danger">
        @ViewBag.Error
    </div>
    <form asp-controller="Cuentas" asp-action="Registrar">

        <div class="form-row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-4">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" autofocus />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Dni" class="control-label"></label>
                <input asp-for="Dni" class="form-control" />
                <span asp-validation-for="Dni" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label class="control-label">Contraseña:</label>
                <input required name="password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>

            </div>
        </div>

        <div class="form-group text-right">
            <input type="submit" value="Registrar Usuario" class="btn btn-success btn3d" />

        </div>

    </form>
</div>
<div>
    <a asp-controller="Home" asp-action="Index">Volver</a>
</div>